version: "3.9"

services:
  db:
    image: postgres:15
    container_name: bancoPostgresAv2BackEnd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca_db
    ports:
      - "3030:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
